name: Simple flake8

<<<<<<< HEAD
on:
  workflow_run:
=======
on: workflow_dispatch
>>>>>>> 01f3a3c (Update .github-ci.yml)

jobs:
  Flake8-test:
    name: Install & run flake8 test
    runs-on: ubuntu-latest
    steps:
      - name: Install dib
        shell: bash
        run: ls -al

      - name: Run flake8
        shell: bash
        run: flake8 -v

