name: Simple flake8

on: [workflow_dispatch, push, pull_request]

jobs:
  Flake8-test:
    name: Install & run flake8 test
    runs-on: ubuntu-22.04
    steps:
      - name: Install flake8
        shell: bash
        run: sudo apt update && sudo apt install flake8
      
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: naestia/dib
          path: .

      - name: Run flake8
        shell: bash
        run: flake8 -v

  Install-and-test:
    name: Install dib & run pytest
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: naestia/dib
          path: .
      
      - name: Install dib
        shell: bash
        run: pip install ".[dev,test]"
      
      - name: Run pytest
        shell: bash
        run: pytest -vv .
