name: Publish to test-pypi & pypi
on:
  release:
    types: [published]
jobs:
  deploy-to-test-pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch_depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  deploy-to-pypi:
    runs-on: ubuntu-22.04
    needs: deploy-to-test-pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch_depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
